[versions]
android-gradle-plugin = "7.2.0-alpha07"
kotlin = "1.6.10"
spotless = "6.2.0"

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
gradlePlugin-spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
dsl = [
    "gradlePlugin-android",
    "gradlePlugin-spotless",
    "gradlePlugin-kotlin",
]
