[versions]
android-gradle-plugin = "7.2.0-alpha01"
kotlin = "1.5.31"
spotless = "5.17.0"

[libraries]
gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
gradle-plugin-spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
dsl = [
    "gradle-plugin-android",
    "gradle-plugin-spotless",
    "gradle-plugin-kotlin",
]
